### ISSUE TITLE
Hopper 4 plugin directory has changed

### ISSUE THREAD

**Issue by robmaceachern** [keith/hopper-swift-demangle#3]
I tried installing the plugin at `~/Library/Application\ Support/Hopper/PlugIns/Tools/` but Hopper 4 didn't load it.

It looks like Hopper 4 expects them to be in `~/Library/Application\ Support/Hopper/PlugIns/v4/Tools/`. H/t to https://github.com/agatti/hopper-plugins#installation-instructions

**Comment by keith** [comment]
I don’t think you should need this plugin anymore actually. Hopper should always demangle for you now. Are you not seeing that behavior?

**Comment by robmaceachern** [comment]
It seems to do parts of it automatically but the procedure names still appear mangled in the main representation panes.
<img width="1058" alt="screen shot 2018-05-02 at 2 29 41 pm" src="https://user-images.githubusercontent.com/430436/39550242-7a575a18-4e15-11e8-8b53-62b8dd62b2aa.png">

After running plugin:
<img width="1056" alt="screen shot 2018-05-02 at 2 30 21 pm" src="https://user-images.githubusercontent.com/430436/39550310-a16863ae-4e15-11e8-87c6-66b7efdfce89.png">

**Comment by keith** [comment]
Interesting! I've updated the paths here: https://github.com/keith/hopper-swift-demangle/pull/5

**Comment by keith** [comment]
Thanks for reporting this!
